name: sledfilm
favicon: null
layout_spectrum: 0.393717109458521
typography_spectrum: 0.5627510342746973
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fff6d8'
    - '#839d9c'
    - '#ff363b'
    - '#56524a'
  brandStrength: 0.75
  lightness: 0.6320564616471529
  saturation: 0.9595361026003957
  rhythmicContrast: 0.5663314396515489
purpose: []
